---
title: "Proyecto"
author: Carlos Gila Blanco y Enrique Sayas Bailach
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  html_notebook:
    echo: yes
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: 3
params:
  lang: ES
lang: r switch(params$lang, ES = 'es-ES', EN = 'en-US')
subtitle: Tratamiento de Datos. Grado en Ciencia de Datos- UV
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# Configuración del los bloques (*Chunks*)

# CONFIGURACIÓN GENERAL
library(knitr)
options(width = 100)

# Opciones generales de los chucks. Se utilizarán salvo cambios en el chunk
opts_chunk$set(echo=T, message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 200, tidy = F, cache.path = '.cache/', fig.path = './figura/')

# Opciones generales de dígitos cuando se incluyen tablas
#options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
#knit_hooks$set(plot = knitr:::hook_plot_html)
```

```{r echo = F, message = F}
# Instalación automática de paquetes

# Especificamos las librerías necesarias en esta lista

packages = c("readr","ggplot2","dplyr","tidyr","stringr","GGally","car")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
  }
  library(x, character.only = TRUE)
})

#verify they are loaded
search()
rm(list = ls())
```

# Introducción al trabajo

# Carga de los datos

```{r}
df <- read_csv("data/df.csv", col_types = cols(...1 = col_skip(), 
    year = col_number()))

summary(df)

df$name[df$`alpha-3` == "CIV"] = "Cote D'Ivoire"
```

# Tansformación a tidy dataset

```{r}
df_tidy <- df %>% pivot_longer(c(renewable, no_renewable), names_to = "type", values_to = "prop")
```

## Categoría de las variables

Vamos a cambiar el tipo de variables de `name`, `alpha-3`, `region` y `sub-region`. Todas ellas serán de tipo factor, con tantos niveles como valores diferentes hayan.

```{r}
df_tidy$name <- as.factor(df_tidy$name)
df_tidy$`alpha-3` <- as.factor(df_tidy$`alpha-3`)
df_tidy$region <- as.factor(df_tidy$region)
df_tidy$`sub-region` <- as.factor(df_tidy$`sub-region`)
df_tidy$type <- as.factor(df_tidy$type)
```

# Análisis Exploratorio

## Análisis Univariante

```{r}
qqPlot(df$CO2)
qqPlot(df$GDP)
qqPlot(df$Population)
```


## Análisis Bivariante

```{r}
df %>% select(year:Population) %>% ggpairs()

df %>% select(year:Population) %>% ggcorr()

df %>% select(year:Population) %>% pairs()
```

```{r}
# Explorar la variable "CO2"
ggplot(df, aes(x=year, y=CO2, color=name)) + 
  geom_line() + 
  theme_bw() +
  labs(title = "Emisiones de CO2 por país y año", 
       x = "Año", 
       y = "Emisiones de CO2") +
  theme(legend.position='none')

# Explorar la variable "GDP"
ggplot(df, aes(x=year, y=GDP, color=name)) + 
  geom_line() + 
  theme_bw() +
  labs(title = "PIB por país y año", 
       x = "Año", 
       y = "PIB") +
  theme(legend.position='none')

# Explorar la relación entre "CO2" y "GDP"
ggplot(df, aes(x=GDP, y=CO2, color=name)) + 
  geom_point() + 
  theme_bw() +
  labs(title = "Relación entre emisiones de CO2 y PIB por país", 
       x = "PIB", 
       y = "Emisiones de CO2") +
  theme(legend.position='none')

```

```{r}
# Explorar la relación entre "CO2" y "Population"
ggplot(df, aes(x=Population, y=CO2, color=name)) + 
  geom_point() + 
  theme_bw() +
  labs(title = "Relación entre emisiones de CO2 y población por país", 
       x = "Población", 
       y = "Emisiones de CO2") +
  theme(legend.position='none')

# Explorar la distribución de las emisiones de CO2 por año y continente
ggplot(df, aes(x=CO2, fill=region)) + 
  geom_histogram(bins = 70) + 
  facet_wrap(~year) +
  theme_bw() +
  labs(title = "Distribución de emisiones de CO2 por continente y año", 
       x = "Emisiones de CO2", 
       y = "Frecuencia")

# Explorar la evolución del consumo de electricidad por país y año
ggplot(df, aes(x=year, y=total_electricity, color=name)) + 
  geom_line() + 
  theme_bw() +
  labs(title = "Consumo de electricidad por país y año", 
       x = "Año", 
       y = "Consumo de electricidad") +
  theme(legend.position='none') +
  xlim(2000,2019)

# Explorar la distribución del PIB por subregión
ggplot(df, aes(x=GDP, fill= `sub-region`)) + 
  geom_histogram(bins = 90) + 
  theme_bw() +
  labs(title = "Distribución del PIB por subregión", 
       x = "PIB", 
       y = "Frecuencia") +
  xlim(0, 1.5*10^13) +
  ylim(0, 1000)
```

```{r}
# Gráfico de barras con etiquetas de texto para mostrar los países con mayor emisión de CO2 en 2019
df %>%
  filter(year == 2019) %>%
  arrange(desc(CO2)) %>%
  head(10) %>%
  ggplot(aes(x=name, y=CO2)) +
  geom_bar(stat="identity", fill="#9ecae1") +
  geom_text(aes(label=floor(CO2))) +
  coord_flip() +
  theme_bw() +
  labs(title = "Países con mayor emisión de CO2 en 2019", 
       x = "", 
       y = "Emisiones de CO2")

# Gráfico de burbujas que muestra la relación entre emisiones de CO2 y PIB per cápita
df %>%
  filter(year == 2019 & !is.na(GDP/Population)) %>%
  ggplot(aes(x=GDP/Population, y=CO2, size=Population, color=region)) +
  geom_point(alpha=0.7) +
  scale_size(range=c(1,10)) +
  theme_bw() +
  labs(title = "Relación entre emisiones de CO2 y PIB per cápita", 
       x = "PIB per cápita", 
       y = "Emisiones de CO2")

# Gráfico de área para mostrar la evolución de las emisiones de CO2 por región
df %>%
  group_by(region, year) %>%
  summarize(total_CO2 = sum(CO2)) %>%
  ggplot(aes(x=year, y=total_CO2, fill=region)) +
  geom_area() +
  theme_bw() +
  labs(title = "Evolución de las emisiones de CO2 por región", 
       x = "Año", 
       y = "Emisiones de CO2")
```










